version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manoj
      POSTGRES_DB: cron
    ports:
      - "5432:5432"
    networks:
      - app-network

  cron-app:
    build:
      dockerfile: ./Dockerfile # Replace with the path to your Nest.js app's Dockerfile
    container_name: cron-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: manoj
      DB_NAME: cron
      DB_PORT: 5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
